#!/bin/bash

OUTPUT="eDP-1"

STATE=$(swaymsg -t get_outputs | jq -r ".[] | select(.name==\"$OUTPUT\") | .active")

if [ "$STATE" = "true" ]; then
    swaymsg output "$OUTPUT" disable
else
    swaymsg output "$OUTPUT" enable
fi
