# Default colors
background #282828
foreground #ebdbb2

# Font settings
font_family MesloLGS Nerd Font
font_size 13.0

# Window settings
hide_window_decorations yes
window_padding_width 4

# disable bell sound
enable_audio_bell no
