################################################################################
#                            Font Configuration                                #
################################################################################
# Set the font to use for the terminal (MesloLGS Nerd Font, size 12)
font=JetBrainsMono:size=12

################################################################################
#                            Padding Configuration                             #
################################################################################
# Set padding for the terminal window (5px vertical, 10px horizontal)
pad=5x10

################################################################################
#                            Color Scheme Configuration                        #
################################################################################
# Default background and foreground colors for the terminal
[cursor]
color=faf4ed 575279

[colors]
# Background and foreground colors
background=faf4ed
foreground=575279

# Regular colors
regular0=f2e9e1     # Black (Overlay)
regular1=b4637a     # Red (Love)
regular2=56949f     # Green (Foam)
regular3=ea9d34     # Yellow (Gold)
regular4=286983     # Blue (Pine)
regular5=907aa9     # Magenta (Iris)
regular6=d7827e     # Cyan (Rose)
regular7=575279     # White (Text)

# Bright colors
bright0=fffdf5      # Bright Black (Lighter Overlay)
bright1=df8aa0      # Bright Red (Lighter Love)
bright2=7ebcc7      # Bright Green (Lighter Foam)
bright3=ffc55c      # Bright Yellow (Lighter Gold)
bright4=538faa      # Bright Blue (Lighter Pine)
bright5=b8a1d2      # Bright Magenta (Lighter Iris)
bright6=ffaaa5      # Bright Cyan (Lighter Rose)
bright7=7c76a0      # Bright White (Lighter Text)

# Additional highlight color
flash=ea9d34        # Yellow (Gold)

