################################################################################
#                            Color Scheme Configuration                        #
################################################################################
import = ["~/.config/alacritty/rose-pine.toml"]

################################################################################
#                            Font Configuration                                #
################################################################################
# Font settings
[font]
size = 12  # Set font size to 12

[font.normal]
family = "JetBrainsMono NFM"  # Font family

################################################################################
#                            Window Configuration                              #
################################################################################
# Window settings
[window]
dynamic_padding = true  # Enable dynamic padding

################################################################################
#                            Padding Configuration                             #
################################################################################
# Set padding for the terminal window (5px vertical, 10px horizontal)
padding = { x = 10, y = 5 }
